### ISSUE TITLE
Create and Test MVP use case

### ISSUE THREAD

**Issue by nielsdrost** [NLeSC/xenon-flow#14]
We need one or more CWL files for the tasks the server needs to be able to perform for the MVP.

**Comment by Maartenvm** [comment]
My first attempt: 
[https://github.com/NLeSC-Storyteller/query-builder-server/tree/master/cwl](https://github.com/NLeSC-Storyteller/query-builder-server/tree/master/cwl)

**Comment by mr-c** [comment]
@Maartenvm Cool -- let me know if you'd like some feedback

**Comment by Maartenvm** [comment]
Well it'd be nice to know if it was the correct syntax, since I've not tested it at all ... :)

@mr-c I have some feedback for you though ... 
I couldn't really find in the user guide if it was possible to have command line arguments (as meant in 2.7) in specific positions like the inputBinding positions. f.e.

**Comment by Maartenvm** [comment]
@nielsdrost @jmaassen Please be aware the ID parameter is actually not something I'd like to give _to_ Xenon-CWL, but should be generated _by_ Xenon-CWL, as in a unique ID for the job.

(at the client side to this service, I'd just want to add a job, not think about what ID that job should have in advance)

**Comment by bpmweel** [comment]
2739522 includes a number of cwl files that are used in integration tests.

More tests will come from implementing a command line runner and using the cwl conformance test.
