### ISSUE TITLE
Find simple webdav server (preferably in Java)

### ISSUE THREAD

**Issue by nielsdrost** [NLeSC/xenon-flow#15]

**Comment by jmaassen** [comment]
One example is milton.io

**Comment by sverhoeven** [comment]
For download only I would use the [jetty resourcehandler](http://download.eclipse.org/jetty/stable-9/apidocs/org/eclipse/jetty/server/handler/ResourceHandler.html) to host a local directory under a url.
Then you don't need any additional dependencies.

**Comment by bpmweel** [comment]
We tried using the spring-boot embedded webdav, however this did not give us the results we wanted.

1. There is no user sercurity
2. I could not get the CORS to be set correctly (tried for about 4 hours).

Perhaps we should assume a external webdav?

I've been currently working with a local folder as in and output instead of webdav. As this is now configurable and using xenon anyways, perhaps we should not supply a webdav at all.

**Comment by bpmweel** [comment]
The current solution of hosting a local directory works quite well. For more advanced use users can set up a separate webdav server.
